---
# install dependencies

- name: update ubuntu
  apt:
    update_cache: yes
    upgrade: dist

- name: install dependencies
  apt:
    name: ['python3-dev', 'python3-pip', 'supervisor']
    state: present

- name: install libsm6 and libxrender1
  apt:
    name: ['libsm6', 'libxrender1', 'libfontconfig1']
    state: present
    update_cache: yes

- name: Add postgres-9.6 repository
  apt_repository:
    repo: "deb https://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main"
    state: present
    update_cache: yes

- name: Add postgres-9.6 apt key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: install postgres-9.6
  apt:
    name: ['postgresql-9.6']
    state: present
    update_cache: yes

- include_tasks: wkhtmltopdf_install.yml
    
- name: upgrade pip
  pip:
    name: pip
    extra_args: --upgrade

- name: install virtualenvwrapper
  pip:
    name: virtualenvwrapper
